### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by kanchar** [Isilon/isilon_stat_browser#19]
Hi There,

I am getting the following error when i run build stat browser.py

Traceback (most recent call last):
  File "build_stat_browser.py", line 68, in <module>
    build_browser()
  File "build_stat_browser.py", line 63, in build_browser
    bb.build_browser()
  File "C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\browser_builder.py", line 130, in build_browser
    key_data = self._write_key_data_json(jskeys_path)
  File "C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\browser_builder.py", line 102, in _write_key_data_json
    self.password)
  File "C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\key_collector.py", line 123, in get_tagged_squashed_di
    key_dict = _get_key_dict(cluster_ip, username, password)
  File "C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\key_collector.py", line 111, in _get_key_dict
    key_list = _get_key_list(cluster_ip, username, password)
  File "C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\key_collector.py", line 97, in _get_key_list
    papi = isi_sdk.ApiClient(host)
  File "C:\Users\skanchar\AppData\Local\Programs\Python\Python36\lib\site-packages\isi_sdk_7_2\api_client.py", line 71, in __init__
    self.rest_client = rest.RESTClientObject(configuration)
  File "C:\Users\skanchar\AppData\Local\Programs\Python\Python36\lib\site-packages\isi_sdk_7_2\rest.py", line 68, in __init__
    if configuration.verify_ssl:
AttributeError: 'str' object has no attribute 'verify_ssl'

**Comment by dmtucker** [comment]
@kanchar What version of `isi_sdk_7_2` do you have?
``` sh
pip show isi_sdk_7_2
```

**Comment by kanchar** [comment]
Hi David,

Thanks for quick response

C: pip show isi_sdk_7_2
Name: isi-sdk-7-2
Version: 0.2.5
Summary: Isilon SDK
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: sdk@isilon.com
License: UNKNOWN
Location: c:\users\skanchar\appdata\local\programs\python\python36\lib\site-packages
Requires: urllib3, six, certifi, python-dateutil
Required-by:

**Comment by dmtucker** [comment]
I suspect you need `isi_sdk_7_2 ~= 0.1.2`. Could you try downgrading?
``` sh
pip install 'isi_sdk_7_2 ~= 0.1.2'
```

**Comment by kanchar** [comment]
Hi David,

Name: isi-sdk-7-2
Version: 0.1.2
Summary: Isilon SDK
Home-page: https://github.com/Isilon/isilon_sdk
Author: UNKNOWN
Author-email: sdk@isilon.com
License: UNKNOWN
Location: c:\users\skanchar\appdata\local\programs\python\python36\lib\site-packages
Requires: urllib3, certifi, python-dateutil, six
Required-by:

*******************************************

C:\junk\script\isilon\stat_browser\isilon_stat_browser-master>python build_stat_browser.py --debug
Cluster IP or hostname:
Cluster username: admin
Password:
2019-02-08T08:21:15 [DEBUG] Querying cluster for stat key list
Traceback (most recent call last):
  File "build_stat_browser.py", line 68, in <module>
    build_browser()
  File "build_stat_browser.py", line 63, in build_browser
    bb.build_browser()
  File "C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\browser_builder.py", line 130, in build_browser
    key_data = self._write_key_data_json(jskeys_path)
  File "C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\browser_builder.py", line 103, in _write_key_data_json
    key_dict = self._transform_key_dict(key_dict)
  File "C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\browser_builder.py", line 89, in _transform_key_dict
    tagger = Tagger()
  File "C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\tagger.py", line 26, in __init__
    def_path = self.get_defs_path()
  File "C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\tagger.py", line 73, in get_defs_path
    logging.debug('Expect key tag definitions at ', path=defs_path)
  File "C:\Users\skanchar\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1911, in debug
    root.debug(msg, *args, **kwargs)
  File "C:\Users\skanchar\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1295, in debug
    self._log(DEBUG, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'path'

**Comment by dmtucker** [comment]
That looks like a legitimate (although separate) bug.
Does it reproduce if you omit `--debug`?

**Comment by kanchar** [comment]
C:\junk\script\isilon\stat_browser\isilon_stat_browser-master>python build_stat_browser.py
Cluster IP or hostname:
Cluster username:
Password:
2019-02-08T09:08:17 [ERROR] Unable to open C:\junk\script\isilon\stat_browser\isilon_stat_browser-master\stat_key_browser\data\key_tags.json: [Errno 2
] No such file or directory: 'C:\\junk\\script\\isilon\\stat_browser\\isilon_stat_browser-master\\stat_key_browser\\data\\key_tags.json'
2019-02-08T09:08:17 [ERROR] Try running 'make tags' to create the tag file

**Comment by dmtucker** [comment]
Did `make tags` help?

**Comment by kanchar** [comment]
Sorry david I am new to programming

I don’t know what “make tags” does or how to run it.

Os: windows 7

Thanks

**Comment by dmtucker** [comment]
Ah, `make` refers to [GNU Make](https://www.gnu.org/software/make/). If you don't have that installed or don't want to bother with it, you can just do what `make tags` does under the hood:
https://github.com/Isilon/isilon_stat_browser/blob/c0368c079c73f44b6b1a49a4605920efe48a17c4/Makefile#L20-L21
``` sh
./hexaparse.py stat_key_browser/data/key_tags.hexa > stat_key_browser/data/key_tags.json 
./hexaparse.py stat_key_browser/data/key_cats.hexa > stat_key_browser/data/key_cats.json
```

**Comment by kanchar** [comment]
Hi David,

Thank you heaps for your help
